- name: update and install docker
  hosts: _development
  become: true
  tasks:
    - name: update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: remove old docker packeges
      ansible.builtin.yum:
        name: 
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

    - name: install yum utils
      ansible.builtin.yum:
        name: yum-utils
        state: latest 

    - name: add docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest : /etc/yum.repos.d/docer-ce.repo  

    - name: install docker
      ansible.builtin.package:
        name: docker-ce
        state: latest 

    - name: Add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes  

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes